//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS2.AdminFolder {
    
    
    public partial class Management {
        
        /// <summary>
        /// AdminNavControlHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ABS2.Controls.AdminNavControl AdminNavControlHome;
        
        /// <summary>
<<<<<<< HEAD
//<<<<<<< HEAD
        /// TextBox1 control.
//=======
        /// form1 control.
//>>>>>>> b3fda193e2b783cf538db80cb569fde9c7170d4c
=======
//<<<<<<< HEAD
        /// TextBox1 control.
//=======
        /// form1 control.
//>>>>>>> b3fda193e2b783cf538db80cb569fde9c7170d4c
>>>>>>> 8ceea42e9a3e861a49e2645741bce1d32036c870
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
//<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
//=======
=======
//<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
//=======
>>>>>>> 8ceea42e9a3e861a49e2645741bce1d32036c870
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// calTxtBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox calTxtBox;
        
        /// <summary>
        /// calTxtBox_CalendarExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender calTxtBox_CalendarExtender;
        
        /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// grdAvailability control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView grdAvailability;
        
        /// <summary>
        /// ObjectDataSource1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource ObjectDataSource1;
<<<<<<< HEAD
//>>>>>>> b3fda193e2b783cf538db80cb569fde9c7170d4c
=======
//>>>>>>> b3fda193e2b783cf538db80cb569fde9c7170d4c
>>>>>>> 8ceea42e9a3e861a49e2645741bce1d32036c870
    }
}
